currency-exchange-service:
  API_URL: "https://free.currconv.com/api/v7/convert?q=%s_%s&compact=ultra&apiKey=9f4a133883a20e901e8d"
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
